#!/usr/bin/env bash
# configure load balancer with HAproxy.
sudo apt-get update
sudo apt-get -y install haproxy
printf "\nfrontend firstbalance\n
\tbind *:80\n
\tmode http\n
\toption forwardfor\n
\tdefault_backend webservers\n\n
backend webservers\n\
\tbalance roundrobin\n
\tserver 17196-web-01 44.200.122.237:80\n
\tserver 17196-web-02 3.237.48.14:80\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start