#!/usr/bin/env bash
# install and configure HAprozy in the server
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cat >> /etc/haproxy/haproxy.cfg << EOL
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 17196-web-01 44.200.122.237:80 check
    server 17196-web-02 3.237.48.14:80 check
EOL
sudo /etc/init.d/haproxy restart
